<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AppointmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('appointments')->insert([
            [
                'patient_id' => 1,
                'appointed_doctor_id' => 2,
                'added_by_id' => 1,
                'appointment_date' => Carbon::now()->addDays(1)->format('Y-m-d'),
                'appointment_time' => '09:00:00',
                'status' => 'scheduled',
                'room_number' => '101',
                'appointment_fee' => 150.00,
                'reason' => 'Regular Checkup',
                'notes' => 'First visit for patient',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 2,
                'appointed_doctor_id' => 1,
                'added_by_id' => 1,
                'appointment_date' => Carbon::now()->addDays(2)->format('Y-m-d'),
                'appointment_time' => '10:30:00',
                'status' => 'scheduled',
                'room_number' => '102',
                'appointment_fee' => 450.00,
                'reason' => 'Follow-up',
                'notes' => 'Patient follow-up after surgery',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 3,
                'appointed_doctor_id' => 2,
                'added_by_id' => 1,
                'appointment_date' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'appointment_time' => '14:00:00',
                'status' => 'pending',
                'room_number' => '103',
                'appointment_fee' => 750.00,
                'reason' => 'Consultation',
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 4,
                'appointed_doctor_id' => 3,
                'added_by_id' => 2,
                'appointment_date' => Carbon::now()->addDays(4)->format('Y-m-d'),
                'appointment_time' => '08:30:00',
                'status' => 'scheduled',
                'room_number' => '104',
                'appointment_fee' => 300.00,
                'reason' => 'Dental Cleaning',
                'notes' => 'Annual dental checkup and cleaning',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 5,
                'appointed_doctor_id' => 4,
                'added_by_id' => 1,
                'appointment_date' => Carbon::now()->addDays(5)->format('Y-m-d'),
                'appointment_time' => '16:00:00',
                'status' => 'cancelled',
                'room_number' => '105',
                'appointment_fee' => 200.00,
                'reason' => 'Vaccination',
                'notes' => 'Cancelled due to patient illness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 6,
                'appointed_doctor_id' => 2,
                'added_by_id' => 2,
                'appointment_date' => Carbon::now()->addDays(1)->format('Y-m-d'),
                'appointment_time' => '11:15:00',
                'status' => 'scheduled',
                'room_number' => '106',
                'appointment_fee' => 120.00,
                'reason' => 'Blood Test',
                'notes' => 'Routine blood test for cholesterol check',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 7,
                'appointed_doctor_id' => 5,
                'added_by_id' => 2,
                'appointment_date' => Carbon::now()->addDays(2)->format('Y-m-d'),
                'appointment_time' => '13:45:00',
                'status' => 'completed',
                'room_number' => '107',
                'appointment_fee' => 500.00,
                'reason' => 'Eye Examination',
                'notes' => 'Prescription updated for new lenses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 8,
                'appointed_doctor_id' => 6,
                'added_by_id' => 2,
                'appointment_date' => Carbon::now()->addDays(6)->format('Y-m-d'),
                'appointment_time' => '17:30:00',
                'status' => 'pending',
                'room_number' => '108',
                'appointment_fee' => 650.00,
                'reason' => 'Cardiology Consultation',
                'notes' => 'High blood pressure monitoring',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 9,
                'appointed_doctor_id' => 3,
                'added_by_id' => 1,
                'appointment_date' => Carbon::now()->addDays(7)->format('Y-m-d'),
                'appointment_time' => '09:45:00',
                'status' => 'scheduled',
                'room_number' => '109',
                'appointment_fee' => 300.00,
                'reason' => 'Orthopedic Checkup',
                'notes' => 'Knee pain after injury',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_id' => 10,
                'appointed_doctor_id' => 1,
                'added_by_id' => 2,
                'appointment_date' => Carbon::now()->addDays(8)->format('Y-m-d'),
                'appointment_time' => '15:00:00',
                'status' => 'scheduled',
                'room_number' => '110',
                'appointment_fee' => 800.00,
                'reason' => 'Emergency Consultation',
                'notes' => 'Severe headache and dizziness',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
