<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    { 
         DB::table('doctors')->insert([
            [
                'doctor_id' => 3,
                'department_id' => 1,
                'description' => 'Heart specialist focusing on surgery',
                'specialization' => 'Heart Surgery',
                'qualification' => 'MD, Cardiology',
                'experience_years' => 10,
                'gender' => 'Male',
                'address' => '123 Main Street',
                'hospital_id' => 1,
                'added_by_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 4,
                'department_id' => 2,
                'description' => 'Brain specialist',
                'specialization' => 'Brain Surgery',
                'qualification' => 'MD, Neurology',
                'experience_years' => 8,
                'gender' => 'Female',
                'address' => '456 Elm Street',
                'hospital_id' => 1,
                'added_by_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 5,
                'department_id' => 3,
                'description' => 'Child care specialist',
                'specialization' => 'Child Care',
                'qualification' => 'MD, Pediatrics',
                'experience_years' => 5,
                'gender' => 'Male',
                'address' => '789 Oak Avenue',
                'hospital_id' => 2,
                'added_by_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 6,
                'department_id' => 4,
                'description' => 'Eye specialist',
                'specialization' => 'Ophthalmology',
                'qualification' => 'MD, Ophthalmology',
                'experience_years' => 7,
                'gender' => 'Female',
                'address' => '321 Pine Street',
                'hospital_id' => 2,
                'added_by_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 7,
                'department_id' => 5,
                'description' => 'Skin specialist',
                'specialization' => 'Dermatology',
                'qualification' => 'MD, Dermatology',
                'experience_years' => 6,
                'gender' => 'Male',
                'address' => '654 Cedar Avenue',
                'hospital_id' => 1,
                'added_by_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 8,
                'department_id' => 1,
                'description' => 'Heart and lung specialist',
                'specialization' => 'Cardiology',
                'qualification' => 'MD, Cardiology',
                'experience_years' => 12,
                'gender' => 'Female',
                'address' => '987 Maple Street',
                'hospital_id' => 1,
                'added_by_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 9,
                'department_id' => 2,
                'description' => 'Brain and nervous system specialist',
                'specialization' => 'Neurology',
                'qualification' => 'MD, Neurology',
                'experience_years' => 9,
                'gender' => 'Male',
                'address' => '159 Birch Road',
                'hospital_id' => 2,
                'added_by_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 10,
                'department_id' => 3,
                'description' => 'Pediatric specialist',
                'specialization' => 'Pediatrics',
                'qualification' => 'MD, Pediatrics',
                'experience_years' => 4,
                'gender' => 'Female',
                'address' => '753 Spruce Lane',
                'hospital_id' => 2,
                'added_by_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 11,
                'department_id' => 4,
                'description' => 'Eye and vision specialist',
                'specialization' => 'Ophthalmology',
                'qualification' => 'MD, Ophthalmology',
                'experience_years' => 5,
                'gender' => 'Male',
                'address' => '852 Willow Street',
                'hospital_id' => 1,
                'added_by_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doctor_id' => 12,
                'department_id' => 5,
                'description' => 'Skin and cosmetic specialist',
                'specialization' => 'Dermatology',
                'qualification' => 'MD, Dermatology',
                'experience_years' => 7,
                'gender' => 'Female',
                'address' => '456 Aspen Avenue',
                'hospital_id' => 1,
                'added_by_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
    
}
