<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
           // Make sure hospital and user records exist before running this seeder
        $hospital = DB::table('hospital_infos')->first();
        $user = DB::table('users')->first();

        if (!$hospital || !$user) {
            echo "⚠️  Please seed 'users' and 'hospital_infos' tables first.\n";
            return;
        }

        DB::table('patients')->insert([
            [
                'patient_name' => 'John Doe',
                'age' => 28,
                'sex' => 'male',
                'date_of_birth' => '1997-03-12',
                'blood_group' => 'A+',
                'is_admitted' => true,
                'phone_number' => '01710000001',
                'email' => 'john.doe@example.com',
                'address' => 'Dhaka, Bangladesh',
                'emergency_contact_phone' => '01710000002',
                'allergies' => 'Peanuts',
                'chronic_diseases' => 'Asthma',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Maria Rahman',
                'age' => 35,
                'sex' => 'female',
                'date_of_birth' => '1990-05-20',
                'blood_group' => 'O+',
                'is_admitted' => false,
                'phone_number' => '01710000003',
                'email' => 'maria.rahman@example.com',
                'address' => 'Chittagong, Bangladesh',
                'emergency_contact_phone' => '01710000004',
                'allergies' => 'None',
                'chronic_diseases' => 'Hypertension',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Abdul Karim',
                'age' => 40,
                'sex' => 'male',
                'date_of_birth' => '1985-01-15',
                'blood_group' => 'B+',
                'is_admitted' => false,
                'phone_number' => '01710000005',
                'email' => 'abdul.karim@example.com',
                'address' => 'Sylhet, Bangladesh',
                'emergency_contact_phone' => '01710000006',
                'allergies' => 'Penicillin',
                'chronic_diseases' => 'Diabetes',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Nusrat Jahan',
                'age' => 30,
                'sex' => 'female',
                'date_of_birth' => '1995-09-18',
                'blood_group' => 'AB+',
                'is_admitted' => false,
                'phone_number' => '01710000007',
                'email' => 'nusrat.jahan@example.com',
                'address' => 'Rajshahi, Bangladesh',
                'emergency_contact_phone' => '01710000008',
                'allergies' => 'Dust',
                'chronic_diseases' => 'Migraine',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Tanvir Ahmed',
                'age' => 45,
                'sex' => 'male',
                'date_of_birth' => '1980-02-22',
                'blood_group' => 'A-',
                'is_admitted' => true,
                'phone_number' => '01710000009',
                'email' => 'tanvir.ahmed@example.com',
                'address' => 'Khulna, Bangladesh',
                'emergency_contact_phone' => '01710000010',
                'allergies' => 'Seafood',
                'chronic_diseases' => 'Heart Disease',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Sadia Alam',
                'age' => 22,
                'sex' => 'female',
                'date_of_birth' => '2003-07-14',
                'blood_group' => 'B-',
                'is_admitted' => false,
                'phone_number' => '01710000011',
                'email' => 'sadia.alam@example.com',
                'address' => 'Barishal, Bangladesh',
                'emergency_contact_phone' => '01710000012',
                'allergies' => 'None',
                'chronic_diseases' => 'None',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Rafiul Hasan',
                'age' => 33,
                'sex' => 'male',
                'date_of_birth' => '1992-04-25',
                'blood_group' => 'O-',
                'is_admitted' => true,
                'phone_number' => '01710000013',
                'email' => 'rafiul.hasan@example.com',
                'address' => 'Rangpur, Bangladesh',
                'emergency_contact_phone' => '01710000014',
                'allergies' => 'Dust',
                'chronic_diseases' => 'Asthma',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Shamima Akter',
                'age' => 55,
                'sex' => 'female',
                'date_of_birth' => '1970-06-10',
                'blood_group' => 'A+',
                'is_admitted' => false,
                'phone_number' => '01710000015',
                'email' => 'shamima.akter@example.com',
                'address' => 'Comilla, Bangladesh',
                'emergency_contact_phone' => '01710000016',
                'allergies' => 'Pollen',
                'chronic_diseases' => 'Arthritis',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Mahmudul Islam',
                'age' => 38,
                'sex' => 'male',
                'date_of_birth' => '1987-10-19',
                'blood_group' => 'AB-',
                'is_admitted' => false,
                'phone_number' => '01710000017',
                'email' => 'mahmudul.islam@example.com',
                'address' => 'Gazipur, Bangladesh',
                'emergency_contact_phone' => '01710000018',
                'allergies' => 'Shellfish',
                'chronic_diseases' => 'High Cholesterol',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'patient_name' => 'Lamia Chowdhury',
                'age' => 29,
                'sex' => 'female',
                'date_of_birth' => '1996-08-07',
                'blood_group' => 'O+',
                'is_admitted' => true,
                'phone_number' => '01710000019',
                'email' => 'lamia.chowdhury@example.com',
                'address' => 'Mymensingh, Bangladesh',
                'emergency_contact_phone' => '01710000020',
                'allergies' => 'Milk',
                'chronic_diseases' => 'Thyroid Disorder',
                'hospital_id' => $hospital->id,
                'added_by_id' => $user->id,
                'is_active' => true,
                'generated_patient_id' => 'PAT-' . strtoupper(Str::random(6)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
